config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'pages/about'
   root 'project#index'
    
    resources :project do
        resources :task, only: [:show]
    end
    
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
    has_one_attached :image
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :tasks, dependent: :destroy
     has_one_attached :image
    
    validates :name, presence: true, length: {maximum: 50}
    validates :content, presence: true, length: {maximum: 500}
    validates :price, presence: true, numericality: {only_integer: true }
    
end
    
#    has_attached_file :image
#    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    
    
#end
    
#    show do |t|
#        attributes_table do
#            row :name
#            row :content
#            row :price
#            row :image do
#                project.image? ? image_tag(project.image.url, height: '100') : content_tag(:span, "no photo yet")
#            end
#        end
#    end
#    form :html => { :enctype => "multipart/form-data" } do |f|
#        f.input do
#            f.input :name
#            f.input :content
#            f.input :price
#            f.input :image, hint: f.project.image? ? image_tag(project.image.url, height: '100') : content_tag(:span, "upload JPG/PNG/GIf")
#    end
#        f.actions
#    end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
    
  validates :title, presence: true, length: {maximum: 50}
  validates :project, presence: true
  validates :video, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    validates :name, presence: true, length: {maximum: 25}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    
    def configure_permitted_parameters
        
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :remember_me])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :email, :password, :remember_me])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :current_password])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < InheritedResources::Base

  private

    def pin_params
      params.require(:pin).permit(:title, :body, :image)
    end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def index
      @projects = Project.all
  end

  def show
      @project = Project.find(params[:id])
      @tasks = @project.tasks
  end
    
  def new
      @project = Project.new
  end
  
  def create
    project = Project.create!(project_params)
    redirect_to root_path
  end
 
  private
    def project_params
      params.require(:project).permit(:title, :content, :price, :image)
    end
    
    

end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def show
      @project = Project.find(params[:project_id])
      @tasks = @project.tasks
      @task = @tasks.find(params[:id])
  end
end

app/helpers/application_helper.rb
#module ApplicationHelper
#    def avatar_url(user)
#        gravatar_url.id = Digest::MD5::hexdigest(user.email).downcase "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identicon&s=40"
#    end
#end

module ApplicationHelper
def avatar_url(user, size)
gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
gravatar_url= "https://secure.gravatar.com/avatar/#{gravatar_id}.png?d=identicon&s=#{size}"
image_tag(gravatar_url, alt: user.name, class: "circle responsive_img")
end
    
    class CodeRayify < Redcarpet::Render::HTML
        def block_code(code, language)
            CodeRay.scan(code, language).div(:line_numbers => :table)
        end
    end
    
    def markdown(text)
        coderayified = CodeRayify.new(:filter_html => true, :hard_wrap => true)
        options = {
            :fenced_code_blocks => true,
            :no_intra_emphasis => true,
            :autolink => true,
            :strikethrough => true,
            :lax_html_blcoks => true,
            :superscript => true
            }
        
        markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
        markdown_to_html.render(text).html_safe
    end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/admin/project/_form.html.erb
<%= form_with(model: @admin_project, local: true) do |form| %>
  

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %><br>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  
  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/project/show.html.erb
<div class="row">
  <div class="col m6 offset-m3 center">


    <%= image_tag @project_path.image %>


 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code4Pro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
   <%= render partial: 'shared/header' %>
   <%= render partial: 'shared/message' %>
   <main>
       <div class="container">
           <%= yield %>
       </div>
   </main>
   <%= render partial: 'shared/footer' %>
        
  </body>
  
  <script>
   
      $(document).ready(function(){
            $('.sidenav').sidenav();
        $('.dropdown-trigger').dropdown();
    });
      
  </script>

  
</html>

app/views/pages/about.html.erb
<h1>About Me</h1>
<div class="card z-depth-3">
    <div class="card-content black-text">
       <div class="row">
           <div class="col m6">
            <a class="twitter-timeline" href="https://twitter.com/Code4Startup" data-widget-id="587633580509044736">Tweets by @Code4Startup</a>
            <script>!function(d,s,id) {var js, fjs=d.getElementsByTag(s)[0], p=/^http:/.test(d,location)? 'http' : 'https'; if(d.getElementById(id)){js=d.createElement(s); js.id=id; js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document, "script", "twitter-wjs");</script>
        </div>
        <div class="col m6">
            <div class="card-panel grey lighten-5 z-depth-3">
                <div class="valign-wrapper">
                    <div class="col m3">
                        <%= image_tag "monkey.jpg", class: "circle responsive-img" %>
                    </div>
                    <div class="col m9">
                        <span clas="black-text">
                            I don't know what to say, let the world tell you more.
                        </span>
                    </div>
                </div>
            </div>
        </div>
        
       </div>
    </div>
</div>

app/views/pins/_form.html.erb
<%= form_with(model: pin, local: true) do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %><br>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pins</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.title %></td>
        <td><%= pin.body %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pin.title %>
</p>


  <%= image_tag(@pin.image) if @pin.image.attached? %>


<p>
  <strong>Body:</strong>
  <%= @pin.body %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>

app/views/project/_form.html.erb
<%= form_for(@project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %><br>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  
  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/project/index.html.erb
<div class="row">
<br/>

<% @projects.each do |project| %>
<%= link_to project do %>
   <div class="col s12 m6">
      <div class="card">
          <div class="card-content">
              <span class="card-title grey-text text-darken-4">
                  <%= project.name %>
              </span>
          </div>
          
      </div>       
   </div>
 <% end %>
 <% end %>
</div>

app/views/project/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>


<%= link_to 'Back', projects_path %>

app/views/project/show.html.erb
<div class="row">
    <div class="col m4">
       <div class="card z-depth-2">
           <div class="center">
               <h1>€<%= @project.price %></h1>
           </div>
           <div class="card-action center">
               <button class="btn wave-effect waves-light pink darken-2">
                   Take this Project
               </button>
           </div>
       </div> 
    </div>
    <div class="col m4">
       <div class="card z-depth-2">
           <div class="card-content grey-text text-darken-4">
               <h5><%= @project.name %></h5>
               <hr>
               <%= @project.content %>
               
               <div class="collection">
                   <% @tasks.each do |task| %>
                    <% if task.header %>
                    <div class="collection-item active">
                        <i class="mdi-social-school"><%= task.title %> </i>
                    </div>
                    <% else %>
                    
                        <%= link_to [task.project, task], class: "collection-item" do %>
                        <%= task.title %>
                      <% end %>
                    <% end %>
                   <% end %>
               </div>
           </div>
        </div>
    </div>
    

</div>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
<script type="text/javascript"> 
    <% resource.errors.full_messages.each do |msg| %>
    toastr.error('<%= msg %>')
    <% end %>
</script>
<% end %> 

app/views/shared/_footer.html.erb
<footer class="page-footer brown lighten-4">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Code4Pro</h5>
                <p class="grey-text text-lighten-4">Lorem empsum irisem losuious isis ebelusem oirun rutteion eofds k</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Social</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Linkedin</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Code4Pro
            <%= link_to "About Us", pages_about_path, :class => "grey-text text-lighten-4 right"  %>
            </div>
          </div>
        </footer>

app/views/shared/_header.html.erb
<header>
      
      <!-- Dropdown Structure -->
    <ul id="dropdown1" class="dropdown-content">
      <li><%= link_to "My Profile", edit_user_registration_path %></li>
      <li><a href="#!">My Courses</a></li>
      <li class="divider"></li>
      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
    </ul>
  
    <ul id="dropdown2" class="dropdown-content">
        <li><%= link_to "My Profile", edit_user_registration_path %></li>
        <li><a href="#!">My Courses</a></li>
        <li class="divider"></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
    </ul>
      
       <nav class="brown lighten-4 z-depth-2">
           <div class="container">
            <div class="nav-wrapper">
              <a href="#!" class="brand-logo">Code4Pro</a>
              <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
              
               <ul class="right hide-on-med-and-down">
                <li><a href="#">Courses</a></li>
                <% if(!user_signed_in?) %>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <li><%= link_to "Login", new_user_session_path %></li>
                
                <% else %>
                <li><a class="dropdown-trigger valign-wrapper" href="#!" data-target="dropdown1">
                <%= avatar_url(current_user, 40) %>
                <%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
                
                <% end %>
              </ul>
              
            </div>
           </div>
        </nav>
        <ul class="sidenav" id="mobile-demo">
                <li><a href="#">Courses2</a></li>
                <% if(!user_signed_in?) %>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <li><%= link_to "Login", new_user_session_path %></li>
                
                <% else %>
                <li><a class="dropdown-trigger valign-wrapper" href="#!" data-target="dropdown2">
                <%= avatar_url(current_user, 40) %>
                <%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
                
                <% end %>
              
              </ul>
    </header>

app/views/shared/_message.html.erb
 <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       
<!--
      <% unless flash.empty? %>
 
 <script type ="text/javascript">
     <% flash.each do |f| %>
     <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
     toastr[<%= type %>](<%= f[1] %>)
        <% end %>    
</script>
<% end %>-->

<% unless flash.empty? %>
<script type="text/javascript">
    <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
        toastr['<%= type %>']('<%= f[1] %>', '', {"closeButton": false, "debug": false, "positionClass": "toast-bottom-full-width", "onclick": null, "showDuration": "300", "hideDuration": "1000", "timeOut": "5000", "extendedTimeOut": "1000", "showEasing": "swing", "hideEasing": "linear", "showMethod": "fadeIn", "hideMethod": "fadeOut" });
    <% end %>
</script>
<% end %>

app/views/task/show.html.erb
<div class="row">
    <div class="col m4">
        <div class="card z-depth-2">
            <div class="card-content">
               <div class="collection">
                   <% @tasks.each do |task| %>
                    <% if task.header %>
                    <div class="collection-item active">
                        <i class="mdi-social-school"><%= @task.title %> </i>
                    </div>
                    <% else %>
                    
                        <%= link_to [task.project, task], class: "collection-item" do %>
                        <%= task.title %>
                      <% end %>
                    <% end %>
                <% end %>
               </div>
            </div>
        </div>
    </div>
    
    <div class="col m8">
        <div class="card z-depth-2">
            <div class="card-content">
                <%= @task.video %>
            </div>
            <div class="card-action grey-text text-darken-4">
                <h5><%= @task.title %></h5>
                <hr>
                <%= markdown(@task.note) %>
            </div>
        </div>
    </div>
</div>